version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: tubs-ai-relay_server_1
      APP_PORT: 8000

  server:
    image: ghcr.io/beambuilder/tubs-ai-relay:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    environment:
      TUBS_API_KEY: ${TUBS_API_KEY:-}
      TUBS_DEFAULT_MODEL: ${TUBS_DEFAULT_MODEL:-gpt-4o-mini}
      RELAY_API_KEY: ${RELAY_API_KEY:-}
      TUBS_API_KEY_FILE: /data/tubs_api_key
    volumes:
      - ${APP_DATA_DIR}/data:/data
